on:
  push:
    tags: 'v*'

jobs:
  upload-release:
    runs-on: codeberg-small
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - uses: https://code.forgejo.org/actions/forgejo-release@v2
        with:
          direction: upload
          url: https://codeberg.org
          release-notes: ${{ TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
