when:
  - event: push
    branch: main
  - event: pull_request
  - event: tag
    ref: refs/tags/v*

variables:
  - &moodle_image 'moodlehq/moodle-php-apache:8.1'
  - &database_image 'postgres:16-alpine'

matrix:
  MOODLE_BRANCH:
    - MOODLE_405_STABLE

services:
  postgres:
    image: *database_image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
  selenium:
    image: selenium/standalone-chrome:3

steps:
  - name: Initialize moodle-plugin-ci
    image: *moodle_image
    environment:
      MOODLE_BEHAT_WDHOST: http://selenium:4444/wd/hub
      MOODLE_START_BEHAT_SERVERS: NO
      NVM_DIR: /root/.nvm
      NVM_VERSION: "v0.40.1"
    commands:
      - export MOODLE_DIR="$CI_WORKSPACE/../"
      # Update packages and install postgres-client
      - apt update && apt install -y postgresql-client postgresql-client-common
      # Install nvm and NodeJS
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash
      - . $NVM_DIR/nvm.sh
      - nvm install --default --latest-npm lts/jod
      # Install composer
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      # Prepare Behat
      - export IPADDRESS=`grep "$HOSTNAME$" /etc/hosts | awk '/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/ {print $1; exit}'`
      - export MOODLE_BEHAT_WWWROOT="http://$IPADDRESS:8000"
      # Install Moodle CI plugin
      - cd $CI_WORKSPACE/.. && rm -rf ci
      - composer create-project -n --no-dev --no-progress --prefer-dist moodlehq/moodle-plugin-ci ci ^4
      - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
      - chmod u+x ci/bin/moodle-plugin-ci
      # Initialize moodle-plugin-ci
      - rm -fr moodle-plugin-ci-plugins/moodle-booktool_wordimport
      - moodle-plugin-ci add-plugin --branch v1.4.12 ecampbell/moodle-booktool_wordimport
      - moodle-plugin-ci install --plugin $CI_WORKSPACE --db-type=pgsql --db-host=postgres
      # Run behat tests
      - export MOODLE_DIR="$CI_WORKSPACE/../moodle"
     # - php -S $IPADDRESS:8000 -t $MOODLE_DIR > /dev/null 2>&1 &
      - php $MOODLE_DIR/admin/tool/behat/cli/init.php --add-core-features-to-theme --parallel=1 --optimize-runs=@local_ffhs_exam_toolbox

  - name: PHP Lint
    image: *moodle_image
    commands:
      - export PATH="$(cd $CI_WORKSPACE/../ci/bin; pwd):$(cd $CI_WORKSPACE/../ci/vendor/bin; pwd):$PATH"
      - moodle-plugin-ci phplint

  - name: PHP Copy/Paste Detector
    image: *moodle_image
    commands:
      - export PATH="$(cd $CI_WORKSPACE/../ci/bin; pwd):$(cd $CI_WORKSPACE/../ci/vendor/bin; pwd):$PATH"
      - moodle-plugin-ci phpcpd

  - name: PHP Mess Detector
    image: *moodle_image
    commands:
      - export PATH="$(cd $CI_WORKSPACE/../ci/bin; pwd):$(cd $CI_WORKSPACE/../ci/vendor/bin; pwd):$PATH"
      - moodle-plugin-ci phpmd

  - name: Moodle Code Checker
    image: *moodle_image
    commands:
      - export PATH="$(cd $CI_WORKSPACE/../ci/bin; pwd):$(cd $CI_WORKSPACE/../ci/vendor/bin; pwd):$PATH"
      - moodle-plugin-ci codechecker --max-warnings 0

  - name: Moodle PHPDoc Checker
    image: *moodle_image
    commands:
      - export PATH="$(cd $CI_WORKSPACE/../ci/bin; pwd):$(cd $CI_WORKSPACE/../ci/vendor/bin; pwd):$PATH"
      - moodle-plugin-ci phpdoc --max-warnings 0

  - name: Validating
    image: *moodle_image
    commands:
      - export PATH="$(cd $CI_WORKSPACE/../ci/bin; pwd):$(cd $CI_WORKSPACE/../ci/vendor/bin; pwd):$PATH"
      - moodle-plugin-ci validate

  - name: Check upgrade savepoints
    image: *moodle_image
    commands:
      - export PATH="$(cd $CI_WORKSPACE/../ci/bin; pwd):$(cd $CI_WORKSPACE/../ci/vendor/bin; pwd):$PATH"
      - moodle-plugin-ci savepoints

  - name: Mustache Lint
    image: *moodle_image
    commands:
      - export PATH="$(cd $CI_WORKSPACE/../ci/bin; pwd):$(cd $CI_WORKSPACE/../ci/vendor/bin; pwd):$PATH"
      - moodle-plugin-ci mustache

  - name: Grunt
    image: *moodle_image
    environment:
      NVM_DIR: /root/.nvm
      NVM_VERSION: "v0.40.1"
    commands:
      - export PATH="$(cd $CI_WORKSPACE/../ci/bin; pwd):$(cd $CI_WORKSPACE/../ci/vendor/bin; pwd):$PATH"
      # Install nvm and NodeJS
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash
      - . $NVM_DIR/nvm.sh
      - nvm install --default --latest-npm lts/jod
      # Run Grunt
      - moodle-plugin-ci grunt --max-lint-warnings 0

  - name: PHPUnit tests
    image: *moodle_image
    commands:
      - export PATH="$(cd $CI_WORKSPACE/../ci/bin; pwd):$(cd $CI_WORKSPACE/../ci/vendor/bin; pwd):$PATH"
      - moodle-plugin-ci phpunit --fail-on-warning

  - name: Behat features
    image: *moodle_image
    environment:
      MOODLE_BEHAT_WDHOST: http://selenium:4444/wd/hub
      MOODLE_START_BEHAT_SERVERS: NO
    commands:
      - export PATH="$(cd $CI_WORKSPACE/../ci/bin; pwd):$(cd $CI_WORKSPACE/../ci/vendor/bin; pwd):$PATH"
      # Prepare Behat
      - export IPADDRESS=`grep "$HOSTNAME$" /etc/hosts | awk '/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/ {print $1; exit}'`
      - export MOODLE_BEHAT_WWWROOT="http://$IPADDRESS:8000"
      - export MOODLE_DIR="$CI_WORKSPACE/../moodle"
      - php -S $IPADDRESS:8000 -t $MOODLE_DIR > /dev/null 2>&1 &
      - php $MOODLE_DIR/admin/tool/behat/cli/init.php --add-core-features-to-theme --parallel=1 --optimize-runs=@local_ffhs_exam_toolbox
      # Run behat tests
      - moodle-plugin-ci behat --profile chrome
